name: "Install vercel and deploy"
description: "Shared setup for installing pnpm and node and dependencies"

inputs:
  environment:
    description: "The environment to deploy to"
    required: true
    default: "preview"
  vercel-token:
    description: "The Vercel Token"
    required: true

outputs:
  deployment-url:
    description: "The URL of the deployment"

runs:
  using: "composite"
  steps:
    - name: Install Vercel CLI
      shell: bash
      run: pnpm install --global vercel@latest
    - name: Pull Vercel Environment Information
      shell: bash
      run: vercel pull --yes --environment=${{ inputs.environment }} --token=${{ inputs.vercel-token }}
    - name: Build Project Artifacts
      shell: bash
      run: vercel build --token=${{ inputs.vercel-token }}
    - name: Deploy Project Artifacts to Vercel
      id: deploy-step
      shell: bash
      run: |
        if [ "${{ inputs.environment }}" = "production" ]; then
          vercel deploy --prod --prebuilt --token=${{ inputs.vercel-token }} > deployment-url.txt
        else
          vercel deploy --prebuilt --token=${{ inputs.vercel-token }} > deployment-url.txt
        fi
        echo "deployment-url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT
