name: Deploy on Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request_review:
    types: [submitted]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    outputs:
      deployment-url: ${{ steps.deploy-step.outputs.deployment-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Deploy
        uses: ./.github/actions/vercel
        with:
          environment: preview
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
      - name: Assign deployment URL
        id: deploy-step
        run: echo "deployment-url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT
  add-comment:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    needs: deploy-preview
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Comment URL to PR
        env:
          DEPLOYMENT_URL: ${{needs.deploy-preview.outputs.deployment-url}}
        uses: actions/github-script@v6
        id: comment-with-url
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Deployed [preview](${{env.DEPLOYMENT_URL}})"
            })
