name: Deploy Production on Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    tags:
      - "*"

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Deploy
        uses: ./.github/actions/vercel
        with:
          environment: production
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
