name: PR Title Check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  pr_title_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          PR_TITLE="feat(ci): add pr-title-check workflow"
          if [[ ! $PR_TITLE =~ ^(feat|fix|chore|perf)(\(.+\))?:\s.+ ]]; then
            echo "Invalid PR title. Please, use commitlint prefixes."
            exit 1
          fi

