name: Check PR title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  pr_title_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          REGEX="^(feat|fix|chore|docs|perf)(\([^)]+\))?: .+$"
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ ! $PR_TITLE =~ $REGEX ]]; then
            echo "ERROR"
            exit 1
          fi
