name: PR Title Check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  pr_title_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          REGEX="^(feat|fix|chore|docs|perf)(\([^)]+\))?: .+$"
          PR_TITLE="feat(x) add"
          if [[ ! $PR_TITLE =~ $REGEX ]]; then
            echo "ERROR"
            exit 1
          fi

