name: PR Title Check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  pr_title_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          PR_TITLE=$(git log --format=%s -1 ${{ github.event.pull_request.head.sha }})
          if [[ ! $PR_TITLE =~ ^(feat|fix|chore|perf)\*: ]]; then
            echo "Invalid PR title format. Please use one of the following formats: feat*: , fix*: , chore*: , perf*: "
            exit 1
          fi
