name: PR Title Check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  pr_title_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          PR_TITLE = ${{ github.event.pull_request.title }}
          if [[ ! $PR_TITLE =~ ^(feat|fix|chore|perf)(\(.+\))?:\s.+ ]]; then
            echo "Invalid PR title format. Please use one of the following formats: feat(ci): , fix: , chore: , perf: "
            exit 1
          fi
